### ISSUE TITLE
Correct the format

### ISSUE THREAD

**Issue by coderstar1234** [coderstar1234/coderstar1234#2]
Check the margin and padding is not correct

**Comment by coderstar1234** [comment]
k

**Comment by Anubhakri13** [comment]
hello @coderstar1234 ,may you assign this to me?

**Comment by toukirkhan** [comment]
assign this to me please

**Comment by Aahil13** [comment]
Good day. This is very exciting. Please could you assign this to me

**Comment by Emritik** [comment]
i am already correct this thanks to all of you show your interset
